# Generated by Django 4.1 on 2022-09-02 06:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4)])),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=64)),
                ('level', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SubstituteAsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extra', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asks', to='substitute.classleader')),
                ('conditions', models.ManyToManyField(blank=True, related_name='asks', to='substitute.condition')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(max_length=64)),
                ('CL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='substitute.classleader')),
                ('ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='substitute.substituteask')),
            ],
        ),
        migrations.AddField(
            model_name='classleader',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='Cls', to='substitute.course'),
        ),
    ]
