# Generated by Django 4.1 on 2022-09-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituteask',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracted_asks', to='substitute.classleader'),
        ),
        migrations.AlterField(
            model_name='substituteask',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_asks', to='substitute.classleader'),
        ),
    ]
