# Generated by Django 4.1 on 2022-09-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0002_substituteask_contractor_alter_substituteask_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='classleader',
            name='qualification',
            field=models.ManyToManyField(related_name='cls', to='substitute.condition'),
        ),
        migrations.AlterField(
            model_name='classleader',
            name='courses',
            field=models.ManyToManyField(related_name='cls', to='substitute.course'),
        ),
    ]
