# Generated by Django 4.1 on 2022-09-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0004_rename_cl_entry_cl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classleader',
            old_name='qualification',
            new_name='qualifications',
        ),
    ]
