# Generated by Django 4.1 on 2022-09-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0005_rename_qualification_classleader_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='substituteask',
            name='reason',
            field=models.TextField(default='内定式'),
            preserve_default=False,
        ),
    ]
