# Generated by Django 4.1 on 2022-09-24 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0008_day_level_subject_alter_course_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='substitute.day'),
        ),
        migrations.AddField(
            model_name='substituteask',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='substitute.day'),
        ),
    ]
